/**
 * Shared test texts for all test suites
 * 
 * This module provides standardized test texts across Phase 2 and Orchestrator tests.
 * Texts are organized by language and length (short, medium, long).
 */

export const TEST_TEXTS = {
    english: {
        short: 'THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG',
        medium: 'IN CRYPTOGRAPHY A SUBSTITUTION CIPHER IS A METHOD OF ENCRYPTING BY WHICH UNITS OF PLAINTEXT ARE REPLACED WITH CIPHERTEXT ACCORDING TO A FIXED SYSTEM',
        long: 'THE HISTORY OF CRYPTOGRAPHY BEGINS THOUSANDS OF YEARS AGO UNTIL RECENT DECADES IT HAS BEEN SYNONYMOUS WITH ENCRYPTION THE CONVERSION OF INFORMATION FROM A READABLE STATE TO APPARENT NONSENSE THE ORIGINATOR OF AN ENCRYPTED MESSAGE SHARES THE DECODING TECHNIQUE NEEDED TO RECOVER THE ORIGINAL INFORMATION ONLY WITH INTENDED RECIPIENTS THEREBY PRECLUDING UNWANTED PERSONS FROM DOING THE SAME'
    },
    spanish: {
        short: 'EL VELOZ MURCIELAGO HINDU COMIA FELIZ CARDILLO Y KIWI',
        medium: 'LA CRIPTOGRAFIA ES EL ARTE Y LA CIENCIA DE CIFRAR MENSAJES DE FORMA QUE SOLO LAS PERSONAS AUTORIZADAS PUEDAN LEERLOS Y PROCESARLOS',
        long: 'LA HISTORIA DE LA CRIPTOGRAFIA SE REMONTA A MILES DE AÑOS ATRAS HASTA DECADAS RECIENTES HA SIDO SINONIMO DE CIFRADO LA CONVERSION DE INFORMACION DE UN ESTADO LEGIBLE A UN APARENTE SINSENTIDO EL ORIGINADOR DE UN MENSAJE CIFRADO COMPARTE LA TECNICA DE DECODIFICACION NECESARIA PARA RECUPERAR LA INFORMACION ORIGINAL SOLO CON LOS DESTINATARIOS PREVISTOS IMPIDIENDO ASI QUE PERSONAS NO DESEADAS HAGAN LO MISMO'
    },
    french: {
        short: 'LE RENARD BRUN RAPIDE SAUTE PAR DESSUS LE CHIEN PARESSEUX',
        medium: 'LA CRYPTOGRAPHIE EST LA PRATIQUE ET ETUDE DES TECHNIQUES POUR SECURISER LA COMMUNICATION EN PRESENCE DE TIERS APPELES ADVERSAIRES',
        long: 'LHISTOIRE DE LA CRYPTOGRAPHIE COMMENCE IL Y A DES MILLIERS DANNEES JUSQUA CES DERNIERES DECENNIES ELLE A ETE SYNONYME DE CHIFFREMENT LA CONVERSION DINFORMATIONS DUN ETAT LISIBLE A UN NON SENS APPARENT LAUTEUR DUN MESSAGE CHIFFRE PARTAGE LA TECHNIQUE DE DECODAGE NECESSAIRE POUR RECUPERER LES INFORMATIONS DORIGINE UNIQUEMENT AVEC LES DESTINATAIRES PREVUS EMPECHANT AINSI LES PERSONNES NON DESIREES DE FAIRE DE MEME'
    },
    german: {
        short: 'DER SCHNELLE BRAUNE FUCHS SPRINGT UBER DEN FAULEN HUND',
        medium: 'KRYPTOGRAPHIE IST DIE PRAXIS UND DAS STUDIUM VON TECHNIKEN ZUR SICHEREN KOMMUNIKATION IN GEGENWART DRITTER PARTEIEN DIE ALS GEGNER BEZEICHNET WERDEN',
        long: 'DIE GESCHICHTE DER KRYPTOGRAPHIE BEGINNT VOR TAUSENDEN VON JAHREN BIS VOR KURZEM WAR SIE SYNONYM MIT VERSCHLUSSELUNG DER UMWANDLUNG VON INFORMATIONEN AUS EINEM LESBAREN ZUSTAND IN SCHEINBAREN UNSINN DER URHEBER EINER VERSCHLUSSELTEN NACHRICHT TEILT DIE ZUR WIEDERHERSTELLUNG DER URSPRUNGLICHEN INFORMATIONEN ERFORDERLICHE DECODIERUNGSTECHNIK NUR MIT DEN BEABSICHTIGTEN EMPFANGERN UND VERHINDERT DADURCH DASS UNERWUNSCHTE PERSONEN DASSELBE TUN'
    },
    italian: {
        short: 'LA VELOCE VOLPE MARRONE SALTA SOPRA IL CANE PIGRO',
        medium: 'LA CRITTOGRAFIA E LA PRATICA E LO STUDIO DELLE TECNICHE PER COMUNICAZIONI SICURE IN PRESENZA DI TERZE PARTI CHIAMATE AVVERSARI',
        long: 'LA STORIA DELLA CRITTOGRAFIA INIZIA MIGLIAIA DI ANNI FA FINO A DECENNI RECENTI E STATA SINONIMO DI CIFRATURA LA CONVERSIONE DI INFORMAZIONI DA UNO STATO LEGGIBILE A UN APPARENTE NONSENSO LAUTORE DI UN MESSAGGIO CIFRATO CONDIVIDE LA TECNICA DI DECODIFICA NECESSARIA PER RECUPERARE LE INFORMAZIONI ORIGINALI SOLO CON I DESTINATARI PREVISTI IMPEDENDO COSI ALLE PERSONE INDESIDERATE DI FARE LO STESSO'
    },
    portuguese: {
        short: 'A RAPIDA RAPOSA MARROM PULA SOBRE O CAO PREGUICOSO',
        medium: 'A CRIPTOGRAFIA E A PRATICA E O ESTUDO DE TECNICAS PARA COMUNICACAO SEGURA NA PRESENCA DE TERCEIROS CHAMADOS ADVERSARIOS',
        long: 'A HISTORIA DA CRIPTOGRAFIA COMECA HA MILHARES DE ANOS ATRAS ATE DECADAS RECIENTES TEM SIDO SINONIMO DE CRIPTOGRAFIA A CONVERSAO DE INFORMACOES DE UM ESTADO LEGIVEL PARA UM APARENTE ABSURDO O ORIGINADOR DE UMA MENSAGEM CRIPTOGRAFADA COMPARTILHA A TECNICA DE DECODIFICACAO NECESSARIA PARA RECUPERAR AS INFORMACOES ORIGINAIS APENAS COM OS DESTINATARIOS PRETENDIDOS IMPEDINDO ASSIM QUE PESSOAS INDESEJADAS FACAM O MESMO'
    }
};

/**
 * Get test texts for a specific language
 * 
 * @param {string} language - Language code
 * @returns {Object} Test texts object with short, medium, long
 */
export function getTestTexts(language = null) {
    if (language) {
        return TEST_TEXTS[language] || TEST_TEXTS.english;
    }
    return TEST_TEXTS;
}

/**
 * Get a specific test text
 * 
 * @param {string} language - Language code
 * @param {string} length - Text length ('short', 'medium', 'long')
 * @returns {string} Test text
 */
export function getTestText(language, length = 'medium') {
    const texts = getTestTexts(language);
    return texts[length] || texts.medium;
}

