import { createPhase2TestSuite } from './phase2-test-base.js';

// Test texts for Spanish (short, medium, long)
const testTexts = {
    short: 'EL VELOZ MURCIELAGO HINDU COMIA FELIZ CARDILLO Y KIWI',
    medium: 'LA CRIPTOGRAFIA ES LA DISCIPLINA QUE SE ENCARGA DE ESTUDIAR Y DESARROLLAR TECNICAS DE COMUNICACION SEGURA QUE PERMITEN PROTEGER INFORMACION MEDIANTE EL USO DE CODIGOS Y CIFRADOS',
    long: 'LA CRIPTOGRAFIA HA SIDO UTILIZADA DESDE LA ANTIGUEDAD PARA PROTEGER INFORMACION CONFIDENCIAL EN LA ACTUALIDAD ES FUNDAMENTAL EN LA SEGURIDAD INFORMATICA Y EN LAS COMUNICACIONES DIGITALES PERMITIENDO QUE SOLO LAS PERSONAS AUTORIZADAS PUEDAN ACCEDER A LA INFORMACION PROTEGIDA'
};

const language = 'spanish';

// Create test suite with language-specific texts
createPhase2TestSuite(language, testTexts);

