import { createPhase2TestSuite } from './phase2-test-base.js';

// Test texts for German (short, medium, long)
const testTexts = {
    short: 'FRANZ JAGT IM KOMPLETT VERWAHRLOSTEN TAXI QUER DURCH BAYERN',
    medium: 'KRYPTOGRAPHIE IST DIE WISSENSCHAFT DIE SICH MIT METHODEN BESCHAFTIGT UM NACHRICHTEN FUR DIEJENIGEN UNLESERLICH ZU MACHEN DIE SIE NICHT LESEN SOLLEN UND ERMOGLICHT SICHERE KOMMUNIKATION',
    long: 'KRYPTOGRAPHIE IST EINE ALTE TECHNIK DIE ZUR SCHUTZ VERTRAULICHER INFORMATIONEN VERWENDET WIRD IN DER MODERNEN WELT IST SIE WESENTLICH FUR DIE INFORMATIONS SICHERHEIT UND DIGITALE KOMMUNIKATION UND STELLT SICHER DASS NUR AUTORISIERTE PERSONEN AUF GESCHUTZTE INFORMATIONEN ZUGREIFEN KONNEN'
};

const language = 'german';

// Create test suite with language-specific texts
createPhase2TestSuite(language, testTexts);

