import { createPhase2TestSuite } from './phase2-test-base.js';

// Test texts for Portuguese (short, medium, long)
const testTexts = {
    short: 'UM VEXAME QUANDO JAZIA FRANCISCO PARVA TROUXE',
    medium: 'A CRIPTOGRAFIA E A DISCIPLINA QUE ESTUDA OS METODOS PARA TORNAR AS MENSAGENS ILEGIVEIS PARA AQUELES QUE NAO DEVEM LER E PERMITE COMUNICAR DE FORMA SEGURA',
    long: 'A CRIPTOGRAFIA E UMA TECNICA ANTIGA UTILIZADA PARA PROTEGER INFORMACOES CONFIDENCIAIS NO MUNDO MODERNO E ESSENCIAL PARA A SEGURANCA INFORMATICA E AS COMUNICACOES DIGITAIS GARANTINDO QUE APENAS PESSOAS AUTORIZADAS PODEM ACESSAR AS INFORMACOES PROTEGIDAS'
};

const language = 'portuguese';

// Create test suite with language-specific texts
createPhase2TestSuite(language, testTexts);

