import { createPhase2TestSuite } from './phase2-test-base.js';

// Test texts for French (short, medium, long)
const testTexts = {
    short: 'PORTEZ CE VIEUX WHISKY AU JUGE BLOND QUI FUME',
    medium: 'LA CRYPTOGRAPHIE EST LA DISCIPLINE QUI ETUDIE LES METHODES POUR RENDRE LES MESSAGES ILLISIBLES A CEUX QUI NE DOIVENT PAS LES LIRE ET PERMET DE COMMUNIQUER DE MANIERE SECURISEE',
    long: 'LA CRYPTOGRAPHIE EST UNE TECHNIQUE ANCIENNE UTILISEE POUR PROTEGER LES INFORMATIONS CONFIDENTIELLES DANS LE MONDE MODERNE ELLE EST ESSENTIELLE POUR LA SECURITE INFORMATIQUE ET LES COMMUNICATIONS NUMERIQUES GARANTISSANT QUE SEULES LES PERSONNES AUTORISEES PEUVENT ACCEDER AUX INFORMATIONS PROTEGEES'
};

const language = 'french';

// Create test suite with language-specific texts
createPhase2TestSuite(language, testTexts);

