import { createPhase2TestSuite } from './phase2-test-base.js';

// Test texts for Italian (short, medium, long)
const testTexts = {
    short: 'QUEL VECCHIO TIPO DI JET FUOCO LENTO ZANZARE',
    medium: 'LA CRITTOGRAFIA E LA DISCIPLINA CHE STUDIA I METODI PER RENDERE I MESSAGGI ILLEGGIBILI A CHI NON DEVE LEGGERLI E PERMETTE DI COMUNICARE IN MODO SICURO',
    long: 'LA CRITTOGRAFIA E UNA TECNICA ANTICA UTILIZATA PER PROTEGGERE LE INFORMAZIONI CONFIDENZIALI NEL MONDO MODERNO E ESSENZIALE PER LA SICUREZZA INFORMATICA E LE COMUNICAZIONI DIGITALI GARANTENDO CHE SOLO LE PERSONE AUTORIZZATE POSSONO ACCEDERE ALLE INFORMAZIONI PROTETTE'
};

const language = 'italian';

// Create test suite with language-specific texts
createPhase2TestSuite(language, testTexts);

